#pragma once

#define MAX_EVENTS 128
#define MAX_QUEUE 128
#define MAX_CLIENTS 1000
#define BUFFER_SIZE 1024
#define MAX_BUFFER_SIZE 4096
#define FLUSH_SUCCESS 0
#define FLUSH_ERROR -1
#define FLUSH_PARTIAL 1
#define FLUSH_LATER 2
#define	CHANNEL_LIMIT 42

#define RPL_NOTOPIC "331"
#define RPL_TOPIC "332"
#define RPL_NAMREPLY "353"
#define RPL_ENDOFNAMES "366"